apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  nodeSelector:
  containers:
    - name: python
      image: cdebnath/cisco:v1

      # command: [ "/bin/bash", "-c", "--" ]
      # args: [ "while true; do sleep 30; done;" ]
      command: ["tail", "-f", "/dev/null"]
